version: 2.1
executors:
  node8:
    docker:
      - image: circleci/node:8-jessie
        environment:
          NPM_CONFIG_PREFIX: "~/.npm-global"
    working_directory: ~/repo

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: install npm 6.9.0
          command: sudo npm -g install npm@6.9.0
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
      - run:
          name: prepare test git user
          command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

orbs:
  helix-smoke-tests: adobe/helix-smoke-tests@0.0.4

jobs:
  build:
    executor: node8

    steps:
      - setup
      - run: mkdir junit

      # test & get code coverage
      - run:
          name: Test and Code Coverage
          command: npm run test-ci
          environment:
            MOCHA_FILE: junit/test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  publish-pre-release:
    executor: node8

    steps:
      - setup
      - add_ssh_keys:
          fingerprints:
            - "30:cd:0d:06:00:1f:46:62:f0:dd:af:cb:6f:a5:4f:15"
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json

      - run:
          name: configure npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      # publish pre-releases on master
      - publish-pre-release:
          requires:
            - build
          filters:
            branches:
              only: master
      - build
